@startuml
' uncomment the line below if you're using computer with a retina display
skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
hide methods
hide stereotypes

' entities
' Table(ConfigContex, "ConfigContex\n (config context data)") {
' 	primary_key(id) ObjectId 
' 	not_null(key) VARCHAR
' 	not_null(value) VARCHAR
' 	not_null(name) VARCHAR
' 	not_null(description) VARCHAR
' 	not_null(isActive) BOOLEAN
' 	not_null(createdAt) DATETIME
' 	updatedAt DATETIME
' 	deletedAt DATETIME
' }


Table(users, "users\n (user authentication data)") {
	primary_key(id) INT
	not_null(unique(userId)) VARCHAR[10]
	not_null(firstName) VARCHAR[255]
	not_null(lastName) VARCHAR[255]
	not_null(email) VARCHAR[255]
	not_null(password) VARCHAR[60]
	not_null(isActive) BOOLEAN
	not_null(createdAt) DATETIME
	updatedAt DATETIME
	deletedAt DATETIME
}

Table(emailVerification, "emailVerification\n (email verification token)") {
	primary_key(id) INT
	not_null(unique(token)) TEXT
	not_null(userId) VARCHAR[10]
	not_null(purpose) VARCHAR
	not_null(isActive) BOOLEAN
	not_null(createdAt) DATETIME
	updatedAt DATETIME
	deletedAt DATETIME
}

Table(socialOauth, "socialOauth\n (user social oauth data)") {
	primary_key(id) INT
	not_null(userId) VARCHAR[10]
	not_null(providerName) VARCHAR[10]
	not_null(socialId) VARCHAR
	not_null(socialName) VARCHAR[255]
	not_null(socialEmail) VARCHAR[255]
	not_null(socialPhoto) VARCHAR[255]
	not_null(isActive) BOOLEAN
	not_null(createdAt) DATETIME
	updatedAt DATETIME
	deletedAt DATETIME
}

Table(workspaceData, "workspaceData\n (workspace master data)") {
	primary_key(id) INT
	not_null(unique(spaceId)) VARCHAR[10]
	not_null(name) VARCHAR[255]
	not_null(photo) VARCHAR[255]
	not_null(description) VARCHAR[255]
	not_null(isActive) BOOLEAN
	not_null(createdAt) DATETIME
	updatedAt DATETIME
	deletedAt DATETIME
}

Table(workspaceMember, "workspaceMember\n (workspace member data)") {
	primary_key(id) INT
	not_null(spaceId) VARCHAR[10]
	not_null(userId) VARCHAR[10]
	not_null(roleId) VARCHAR
	not_null(isActive) BOOLEAN
	not_null(createdAt) DATETIME
	updatedAt DATETIME
	deletedAt DATETIME
}

users --> socialOauth : "1:1"
users --> emailVerification : "1:*"
@enduml